### PR TITLE
Add multi-line LongTextEnterActivity

### PR DESCRIPTION
**Pull request by raph431**
I added the option to create QR codes from multi-line texts and created a "Generate QR code" intent-filter, which allows to generate a QR code from any app that can share plain-text content. The android intent filter also allows to regenerate a QR code from a code that was just scanned before. This allows to share a QR code without any losses in picture quality.

### CODE REVIEW

**Comment by Kamuno** [comment]
What exactly is the difference between the LongText and the regular Text? Why can't we just edit the existing text qr code generation page to support longer texts?

**Comment by raph431** [comment]
Sure, we could allow multi-line and longer texts under the current „TextEnterActivity“ as well. I have no preference regarding this question.

**Comment by raph431** [comment]
Do you want me to change it? I can do that, probably a couple hours in the evening.

**Comment by Kamuno** [comment]
If you could do that, that would be great. If not - I can also do it. 😄 Thank you for your contribution.

**Comment by Kamuno** [comment]
Thank you for the PR but as the regular TextEnterActivity can just have an increased limit I will close this PR.

**Pull request closed without merging**
